[package]
name = "vantage-hal"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
[features]
default = ["std"]
std = []
[dependencies]
bytemuck.workspace = true
vantage-raster = { path = "../raster", default-features = false }
vantage-shader = { path = "../shader", default-features = false }
hashbrown.workspace = true
smallvec = { version = "1.16.1", default-features = false }
