[package]
name = "angle_wgpu"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "OpenGL ES 1.1/2.0 and EGL implemented on wgpu, with a C ABI."
include = [
    "src/**/*",
    "cbindgen.toml",
    "include/**/*",
    "LICENSE.txt",
]

[lib]
name = "angle_wgpu"
crate-type = ["rlib", "staticlib"]

[dependencies]
bytemuck = { version = "1.25.2", features = ["derive"] }
cbindgen = "0.29.4"
glam = { version = "0.33.5", default-features = false, features = ["nostd-libm", "all-types"] }
log = "0.4.34"
parking_lot = "0.12.5"
raw-window-handle = { version = "0.6.2", default-features = false }
wgpu = { version = "30.0.1", default-features = false, features = ["wgsl", "vulkan", "gles", "metal"] }
winit = { version = "0.31.0-beta.2", default-features = false, features = ["x11"] }
zune-core = { version = "0.5.3", default-features = false }
zune-png = { version = "0.5.2", default-features = false, features = ["sse", "std"] }

[dev-dependencies]
cbindgen = "0.29.4"

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 2
split-debuginfo = "packed"
