[package]
name = "vantage-egl"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "EGL 1.4 + X11/MIT-SHM presentation for the Vantage software driver."

[lib]
name = "vantage_egl"
crate-type = ["rlib", "staticlib", "cdylib"]


default = ["std", "capi"]
std = ["dep:libloading", "vantage-gles/std"]
capi = []

[dependencies]
vantage-gles = { path = "../gles", default-features = false }
libloading = { version = "0.9.0", default-features = false, optional = true }

[package.metadata.capi.library]
name = "vantage"

[package.metadata.capi.pkg_config]
filename = "glesv1_cm"
name = "glesv1_cm"
library = "vantage"

[package.metadata.capi.install.include]
asset = [
    { from = "include/**/*", to = "." }
]

[package.metadata.capi.install.data]
asset = [
    { from = "glvnd/egl_vendor.d/10_vantage.json", to = "glvnd/egl_vendor.d" },
]
